version: "2"
services: 
   db:
      image: trial7
      hostname: db
      ports: 
         - "33306:3306"
      environment: 
         MYSQL_ROOT_PASSWORD: aidevops
      volumes_from:
         - dbdata
         - dblogs
   dbdata:
      image: centos:centos7
      entrypoint: "true"
      volumes: 
         - /root/docker/dbmaintain2/data/mysql:/data/mysql

   dblogs: 
      image: centos:centos7
      entrypoint: "true"
      volumes:
         - /root/docker/dbmaintain2/logs/mysql:/logs/mysql

